version: '2.3'
services:
  db:
    image: postgres:11
  cron:
    build: .
    image: francisli/primarytracker
    command: bash -l -c "bin/cron"
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_KEY=${CLOUDFLARE_KEY}
      - CLOUDFLARE_ZONE=${CLOUDFLARE_ZONE}
      - DATABASE_URL=postgres://postgres:@db/app
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - sparklines:/opt/node/app/public/images/sparklines
  server:
    build: .
    image: francisli/primarytracker
    command: bash -l -c "npm start"
    environment:
      - APP_NAME=${APP_NAME}
      - ASSET_HOST=${ASSET_HOST}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BASE_URL=${AWS_S3_BASE_URL}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_BUCKET_REGION=${AWS_S3_BUCKET_REGION}
      - BASE_HOST=${BASE_HOST}
      - BASE_URL=${BASE_URL}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_KEY=${CLOUDFLARE_KEY}
      - CLOUDFLARE_ZONE=${CLOUDFLARE_ZONE}
      - DATABASE_URL=postgres://postgres@db/app
      - GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}
      - NODE_ENV=production
      - PORT=3000
      - SESSION_SECRET=${SESSION_SECRET}
      - SMTP_FROM_EMAIL_ADDRESS=${SMTP_FROM_EMAIL_ADDRESS}
    ports:
      - ${HOST_PORT:-3000}:3000
    depends_on:
      - db
    volumes:
      - sparklines:/opt/node/app/public/images/sparklines
volumes:
  sparklines:

